# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

jobs:
- job: Test
  pool:
    vmImage: 'Ubuntu 16.04'

  steps:
  - script: |
      [[ -e "README.mdd" ]] && echo "##vso[task.setvariable variable=isDocCommit]false" || true
    displayName: 'Check commit type'
    
  - script: echo Hello, world!
    condition: ne(variables['isDocCommit'], 'true')
    displayName: 'Run a one-line script'

  - script: |
      echo Add other tasks to build, test, and deploy your project.
      echo $BUILD_SOURCEVERSIONMESSAGE
    condition: eq(variables['isDocCommit'], 'true')
    displayName: 'Run a multi-line script'
